package com.chy.qrcode.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chy.qrcode.dao.SWEEP_RECORD;

import com.chy.qrcode.dao.SWEEP_RECORDDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sWEEP_RECORDDaoConfig;

    private final SWEEP_RECORDDao sWEEP_RECORDDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sWEEP_RECORDDaoConfig = daoConfigMap.get(SWEEP_RECORDDao.class).clone();
        sWEEP_RECORDDaoConfig.initIdentityScope(type);

        sWEEP_RECORDDao = new SWEEP_RECORDDao(sWEEP_RECORDDaoConfig, this);

        registerDao(SWEEP_RECORD.class, sWEEP_RECORDDao);
    }
    
    public void clear() {
        sWEEP_RECORDDaoConfig.clearIdentityScope();
    }

    public SWEEP_RECORDDao getSWEEP_RECORDDao() {
        return sWEEP_RECORDDao;
    }

}
