package com.chy.qrcode.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SWEEP__RECORD".
 */
@Entity
public class SWEEP_RECORD {

    @Id
    private Long id;

    @NotNull
    private String context;
    private Integer tpye;
    private String create_time;

    @Generated
    public SWEEP_RECORD() {
    }

    public SWEEP_RECORD(Long id) {
        this.id = id;
    }

    @Generated
    public SWEEP_RECORD(Long id, String context, Integer tpye, String create_time) {
        this.id = id;
        this.context = context;
        this.tpye = tpye;
        this.create_time = create_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getContext() {
        return context;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContext(@NotNull String context) {
        this.context = context;
    }

    public Integer getTpye() {
        return tpye;
    }

    public void setTpye(Integer tpye) {
        this.tpye = tpye;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

}
